<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "properties"
 *
 * Auto generated by Extension Builder 2015-09-01
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Properties',
	'description' => 'This extension provides functionality for managing properties in TYPO3',
	'category' => 'plugin',
	'author' => 'Arek van Schaijk',
	'author_email' => 'info@ucreation.nl',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);